spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    show-sql: true